title: scATAC Fragment Tools
email: seppe.dewinter@kuleuven.be
description: >- # this means to ignore newlines until "baseurl:"
  Tools for working with scATAC-seq fragment files.
url: "https://aertslab.github.io/scatac_fragment_files" # the base hostname & protocol for your site, e.g. http://example.com

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# Build settings
theme: just-the-docs

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue

